#!/usr/bin/env bash

# shellcheck disable=1090,1091,2046,2048,2068,2086,2206,2207

set -aeuo pipefail

INSTALLDIR=$PWD/conda
UWTOOLS="uwtools=2.13.*"

# In all functions, make variables local unless they are either intended for global use, or set in
# a subshell that exits at the end of the function.

cachedir() {
  (
    conda_activate base
    echo $CONDA_PREFIX/cache
  )
}

conda_activate() {
  local env
  env=$1
  source $INSTALLDIR/etc/profile.d/conda.sh
  # Activation scripts shipped with conda packages may contain statements either expanding undefined
  # variables or exiting with error status, so temporarily disable the checks for these conditions,
  # then enable again.
  set +eu
  conda activate $env
  set -eu
}

conda_create() {
  local name
  name=$1
  shift
  conda_activate base
  msg Creating environment: $name
  conda create -y -q -c ufs-community -n $name $* $UWTOOLS
  (
    # When runtime virtual environments are activated, set XDG_CACHE_HOME so that pip caches package
    # files in the runtime area, rather than in the user's home directory, which might impact their
    # quota. When deactivated, environments should reset or unset this value, as appropriate.
    conda_activate $name
    dir_activate=$CONDA_PREFIX/etc/conda/activate.d
    mkdir -pv $dir_activate
    cat <<EOF >$dir_activate/eagle.sh
if [[ -v XDG_CACHE_HOME ]]; then
  export EAGLE_OLD_XDG_CACHE_HOME=\$XDG_CACHE_HOME
fi
export XDG_CACHE_HOME=$(cachedir)
EOF
    dir_deactivate=$CONDA_PREFIX/etc/conda/deactivate.d
    mkdir -pv $dir_deactivate
    cat <<EOF >$dir_deactivate/eagle.sh
unset XDG_CACHE_HOME
if [[ -v EAGLE_OLD_XDG_CACHE_HOME ]]; then
  export XDG_CACHE_HOME=\$EAGLE_OLD_XDG_CACHE_HOME
  unset EAGLE_OLD_XDG_CACHE_HOME
fi
EOF
  )
}

conda_create_base() {
  local name pkgs
  name=base
  pkgs=(
    $UWTOOLS
  )
  test -v EAGLE_DEV && pkgs+=($(devpkgs))
  conda_install $name -c ufs-community ${pkgs[@]}
}

conda_create_data() {
  local args name pkgs
  name=data
  pkgs=(
    impi_rt=2021.13.*
    mpi4py=4.1.*
    numpy=1.26.4
    pandas=2.3.3
    types-pyyaml
    ufs2arco=0.19.*
  )
  test -v EAGLE_DEV && pkgs+=($(devpkgs))
  args=($name ${pkgs[@]})
  if conda_env_exists $name; then
    conda_install ${args[@]}
  else
    conda_create ${args[@]}
    (
      conda_activate $name
      dir_activate=$CONDA_PREFIX/etc/conda/activate.d
      mkdir -pv $dir_activate
      cat <<EOF >>$CONDA_PREFIX/etc/conda/activate.d/eagle.sh
if [[ -v FI_PSM3_UUID ]]; then
  export EAGLE_OLD_FI_PSM3_UUID=\$FI_PSM3_UUID
fi
export FI_PSM3_UUID=eagle
EOF
      dir_deactivate=$CONDA_PREFIX/etc/conda/deactivate.d
      mkdir -pv $dir_deactivate
      cat <<EOF >>$CONDA_PREFIX/etc/conda/deactivate.d/eagle.sh
unset FI_PSM3_UUID
if [[ -v EAGLE_OLD_FI_PSM3_UUID ]]; then
  export FI_PSM3_UUID=\$EAGLE_OLD_FI_PSM3_UUID
  unset EAGLE_OLD_FI_PSM3_UUID
fi
EOF
    )
  fi
  pip_install $name anemoi-datasets==0.5.* anemoi-graphs==0.9.*
}

conda_create_inference() {
  local args name pkgs
  name=inference
  pkgs=(
    flash-attn=2.8.*
    numpy=2.2.6.*
    python=3.12
  )
  test -v EAGLE_DEV && pkgs+=($(devpkgs))
  args=($name ${pkgs[@]})
  if conda_env_exists $name; then
    conda_install ${args[@]}
  else
    conda_create ${args[@]}
    write_anemoi_activation_scripts $name
  fi
  pip_install $name anemoi-inference==0.10.* anemoi-models==0.13.* eagle-tools
}

conda_create_prewxvx() {
  local args name pkgs
  name=prewxvx
  pkgs=(
    numpy=2.2.6.*
    pandas=2.3.3.*
    python=3.13
    xesmf=0.8.*
  )
  test -v EAGLE_DEV && pkgs+=($(devpkgs))
  args=($name ${pkgs[@]})
  if conda_env_exists $name; then
    conda_install ${args[@]}
  else
    conda_create ${args[@]}
  fi
  pip_install $name eagle-tools
}

conda_create_training() {
  local args name pkgs
  name=training
  pkgs=(
    flash-attn=2.8.*
    numpy=1.26.4.*
    python=3.12
  )
  test -v EAGLE_DEV && pkgs+=($(devpkgs))
  args=($name ${pkgs[@]})
  if conda_env_exists $name; then
    conda_install ${args[@]}
  else
    conda_create ${args[@]}
    write_anemoi_activation_scripts $name
  fi
  pip_install $name anemoi-models==0.13.* anemoi-training==0.10.*
}

conda_create_wxvx() {
  local args name pkgs
  name=wxvx
  pkgs=(
    wxvx=0.7.*
  )
  test -v EAGLE_DEV && pkgs+=($(devpkgs))
  args=($name -c oar-gsl ${pkgs[@]})
  if conda_env_exists $name; then
    conda_install ${args[@]}
  else
    conda_create ${args[@]}
  fi
}

conda_env_exists() {
  name=$1
  (
    conda_activate base
    conda env list --json | jq -r .envs_details[].name | grep -q "^${name}$"
    test $? -eq 0 && msg Found existing conda environment: $name
  )
}

conda_install() {
  local name
  name=$1
  shift
  msg Installing conda packages into environment: $name
  (
    conda_activate $name
    set +eu
    conda install -y -q "$@"
    set -eu
  )
}

cuda_command_file() {
  local path val
  val=${ARGS[cudascript]}
  path=$val
  test -e $path || path=$(dirname $(readlink -f $0))/cuda/$val
  echo $path
}

cuda_release() {
  (
    source $(cuda_command_file)
    nvcc --version | grep release | sed -E 's/^.*release ([0-9]+).*/\1/'
  )
}

devpkgs() {
  local pkgs=(
    go-shfmt=3.13.*
    jq=1.8.*
    mypy=1.19.*
    ruff=0.14.*
    shellcheck=0.11.*
    yamllint=1.38.*
  )
  echo ${pkgs[@]}
}

install_conda() {
  local installer url ver
  if [[ -d $INSTALLDIR ]]; then
    msg Found existing conda installation: $INSTALLDIR
    return
  fi
  ver=25.9.1-0
  installer=Miniforge3-$ver-$(uname -s)-$(uname -p).sh
  url=https://github.com/conda-forge/miniforge/releases/download/$ver/$installer
  msg Installing conda
  wget -nv $url
  bash $installer -bfp $INSTALLDIR
  rm -v $installer
}

msg() {
  echo -e "=> $*"
}

parse_kvargs() {
  local arg key required val
  declare -g -A ARGS
  for arg in $@; do
    IFS="=" read -r key val <<<$arg
    ARGS[$key]=$val
  done
  required="cudascript"
  for arg in $required; do
    test -z "${ARGS[$arg]:-}" && echo Argument $arg= missing && exit 1
  done
  export ARGS
}

pip_install() {
  local name
  name=$1
  shift
  msg Installing pip packages into environment: $name
  (
    conda_activate $name
    pip install $@ | { grep -v "already satisfied" || true; }
  )
}

write_anemoi_activation_scripts() {
  local name=$1
  (
    conda_activate $name
    cat <<EOF >>$CONDA_PREFIX/etc/conda/activate.d/eagle.sh
modules="\$(module --terse list 2>/dev/null | grep -v 'No modules loaded' | tr '\n' ' ')"
if [[ -n "\$modules" ]]; then
  export EAGLE_OLD_MODULES="\$modules"
fi
$(cat $(cuda_command_file))
EOF
    cat <<EOF >>$CONDA_PREFIX/etc/conda/deactivate.d/eagle.sh
module purge 2>/dev/null
if [[ -v EAGLE_OLD_MODULES ]]; then
  module load \$EAGLE_OLD_MODULES
  unset EAGLE_OLD_MODULES
fi
EOF
  )
}

parse_kvargs $@
install_conda
CONDA_OVERRIDE_CUDA=$(cuda_release)
XDG_CACHE_HOME=$(cachedir)
export CONDA_OVERRIDE_CUDA XDG_CACHE_HOME
environments=(base data inference prewxvx training wxvx)
for name in ${environments[@]}; do
  conda_create_$name
done
msg Done
